### ISSUE TITLE
LDAP verifies user, but any password will work

### ISSUE THREAD

**Issue by michaelcalve** [etianen/django-python3-ldap#143]
Hi,

Currently LDAP is filtering for the correct group, hence usernames are working perfectly. However it doesn't matter what password is submitted.

Is there somewhere in your package where I can adjust a setting to make sure that the password submitted is verified against the Microsoft Active Directory?

Also, I am running the django server in windows. Not sure if that would impact this situation.

Thanks!!!!

**Comment by etianen** [comment]
django-python3-ldap performs authentication using bind(). If any password
is working for you, it implies that your ldap server is accepting any
password for bind()!

You may want to investigate why this is!

**Comment by michaelcalve** [comment]
Thank you for your explanation.  Too simple for me to realize at the time.  Turns out I have to bind with the “first last” cn and not the “first.last” username/samaccountname.  

Perhaps there is a setting to convert the samaccountname to cn before authenticating?  

Right now I am just doing string manipulation as most of my company’s ad entries fit the pattern of “.” = “ “

Thanks for your time!

**Comment by michaelcalve** [comment]
And the reason that it was accepting any password was because i was using an “admin” ldap account to override bind credentials instead for each users samaccountname and pw at sign in, lol.  That was my hack, but now that I understand the bind() everything is working well.

**Comment by etianen** [comment]
There is very little standardization with LDAP servers or LDAP clients.
It's pretty annoying. Glad you've made it work!

There is some discussion on the issue tracker about converting cn to
various other types of account IDs, but I don't have enough time to make a
proper feature of it yet. I'm glad your string manipulation hack is
sufficient!

Auto-adding users from LDAP makes sense to me. I can see why another
package might do it differently in order to whitelist users on a service.
In general, I prefer to use a minimal amount of good quality security. This
tends to translate to blacklists rather than whitelists, and stuff "just
working" by default. It's all just personal taste, however, but I'm glad
you like the approach taken by django-python3-ldap! :P
