### ISSUE TITLE
Sync Groups

### ISSUE THREAD

**Issue by ralgozino** [etianen/django-python3-ldap#28]
Hello!

 I'm a Django newbie, but managed to install and use this LDAP Auth, synced all the users in a breeze! Thanks! :) I was wondering if it is possible to sync the LDAP groups also. We are running an old version of OpenLDAP where the membership is in the group attributes and NOT on the user's.

Thanks!

**Comment by Ernest0x** [comment]
> We are running an old version of OpenLDAP where the membership is in the group attributes and NOT on the user's.

First, you need to enable the memberof overlay that automatically creates a memberOf attribute for each user that is added as a member of each group. For existing users, you may readd them in their groups to have their memberOf attribute created and populated accordingly.

After that, since each user entry will now include group membership information, you can write your own function and use it in the LDAP_AUTH_SYNC_USER_RELATIONS setting (introduced in version 0.9.7), implementing the logic for syncing groups and user-group relationships as needed in your environment.

Note: django-python3-ldap does not currently (in version 0.9.7) fetch the memberOf attribute in OpenLDAP (behavior on other servers may vary). Look my pull request #30 for more information.

**Comment by etianen** [comment]
That pull request has now been merged, so see if it helps you out!

**Comment by ralgozino** [comment]
Thanks a lot! I'll give it a try

**Comment by Ernest0x** [comment]
> That pull request has now been merged, so see if it helps you out!

I am not seeing it merged :). Maybe you have merged it in a yet not pushed local branch?

**Comment by frennkie** [comment]
I'm also interested in populating groups in my Django App with data from the LDAP directory (my LDAP uses the groupOfNames (memberOf) scheme).  
As a first step I implemented a sync for staff and superuser status: [customized ldap_auth.py file] (https://github.com/frennkie/django-python3-ldap/blob/ldap-sync-django-groups/django_python3_ldap/ldap_auth.py)  

What do you guys think of this?
Would it make sense to add this directly into django-python3-ldap (the User attributes is_staff and is_superuser are present on (almost?!) every Django project after all..)?

**Comment by etianen** [comment]
I've seen a lot of weird LDAP setups, which makes we worry that too much
stuff built in to the library will just be confusing for most people.

I'm thinking that using the wiki for sharing these sort of snippets might
be a good idea, and linking to it from the readme. What do you think?

**Comment by frennkie** [comment]
I completely agree with your concern regarding putting too much into the library.
A wiki might really be a good place to collect some examples (although that could even go into a "examples" dir (I've seen that on a couple of projects)).

Do you have some suggestings on improving my code? I'm not happy with the names I have come up so far..
Additionally I am considering pulling even more groups (like "django_app_hr" , "django_app_sales", "django_app_it") from LDAP. For that I would definetly need to make the code more generic. 
Any suggestions?

**Comment by etianen** [comment]
I'd do something like this:

https://gist.github.com/etianen/8ac5a8c6bedfa53f42f5f41c2a1b4c2b

The code's not tested, but it's the general idea. It aims to minimize the number of DB queries required to sync the information in the LDAP memberOf field.
