### ISSUE TITLE
Multiple LDAP servers?

### ISSUE THREAD

**Issue by jeremytiki** [etianen/django-python3-ldap#50]
Is there a way to use a iterable of servers and make multiple attempts to connect to each? For example:

`LDAP_AUTH_URL = ("ldap://0.0.0.1:389", "ldap://0.0.0.2:389", ldap://0.0.0.3:398",)`

**Comment by etianen** [comment]
I'm afraid not. It would be a cool feature.

**Comment by mnach** [comment]
I've red [ldap3 documentation](http://ldap3.readthedocs.io/servers.html#server-pool) about this topic. It looks not so hard.. 
ldap3 has ServerPool [since 0.9.5.4](http://ldap3.readthedocs.io/changelog.html) version, so all we need is just use it

The simpliest implementation is to check is `LDAP_AUTH_URL` iterable and not str when [connection needs to be created](https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L136). If so, create connection from ServerPool. And use Server if `LDAP_AUTH_URL` is just a str.

Also, "Pooling strategy" can be set in another setting-parameter, to fit LDAP-servers configuration. As far as I can see, If second server is just a backup, then it's better to use `FIRST`; if both servers have active role then `ROUND_ROBIN` or `RANDOM` is better.

There are another setting -  `POOLING_LOOP_TIMEOUT`, but I don't know is it better to set it from settings or just hard-code it

I have a two ldap-servers at my work, so I can use them to check this feature and to implement new logic in this library.

**Comment by etianen** [comment]
So the aim here is to have ldap failover? Or to run the same query on multiple servers, returning the first match?

**Comment by mnach** [comment]
Yes, failover and, I guess, lower response time. Single query runs on single server. But if some server in the pool is unavailable - query runs on second one. So, until at least one server is working - ldap auth works fine.
Sistem administrator in my company said that sometimes they have to reboot or halt one of AD servers, so our projects must be configured for using at least two ldap-servers

**Comment by etianen** [comment]
Makes sense. I'm happy to take a pull request that allows LDAP_AUTH_URL to
be a tuple or list of strings.

**Comment by mnach** [comment]
Do I need to do it backward compatible? If LDAP_AUTH_URL is string - use current logic.

Don't you mind if I create another parameter for "Pooling strategy"? With available options: "FIRST", "ROUND_ROBIN" and "RANDOM".

**Comment by etianen** [comment]
For consistency, I'd always create a server pool. Whether LDAP_AUTH_URL is
a string or tuple/list.

I'd preserve backwards compatitbility by allowing LDAP_AUTH_URL to be a
string, as well as a tuple/list. Either way, it'll create a server pool.

LDAP_AUTH_POOLING_STRATEGY is a good idea for a new setting. I'd use the
constants defined in ldap3 for the setting value, though, rather than a
string.

Thanks for puting the time into this!

**Comment by WilliamZimmermann** [comment]
Hello! Is this feature already available? If yes, how can I add other URLs/servers?

**Comment by etianen** [comment]
Nope, sorry. I've not received a pull request, and don't have time to do
the work myself.

**Comment by WilliamZimmermann** [comment]
Ok, no problem. Thank you anyway @etianen .

**Comment by jeremytiki** [comment]
@etianen I'm working on a PR for this, just not sure how to run testing on this project. I believe I have everything working, but I would like to run the tests locally first, is there any recommended way to run the tests for this project before initiating the PR? Sorry if this is an obvious question.

**Comment by etianen** [comment]
You can set the following environment variables to point at your own LDAP
server when running the tests:

LDAP_AUTH_URL
LDAP_AUTH_SEARCH_BASE
LDAP_AUTH_TEST_USER_USERNAME
LDAP_AUTH_TEST_USER_PASSWORD

Thanks for putting the work into this!

**Comment by azbassiouny** [comment]
> So the aim here is to have ldap failover? Or to run the same query on multiple servers, returning the first match?

@etianen what about the latter case "run the same query on multiple servers, returning the first match" any ideas?

**Comment by etianen** [comment]
I have no idea whether the underlying LDAP library supports that approach, sorry. Their docs are here if you want to investigate:

https://ldap3.readthedocs.io/en/latest/
