### ISSUE TITLE
Exception Type: ImportError Exception Value: No module named 'django_python3_ldap.auth'

### ISSUE THREAD

**Issue by DarnelleF** [etianen/django-python3-ldap#56]
Request Method: 	POST
Request URL: 	http://laisydev.slnet.bov.lc:8483/parcelmanager/authenticatedLogin/
Django Version: 	1.8
Exception Type: 	ImportError
Exception Value: 	

No module named 'django_python3_ldap.auth'

Exception Location: 	/usr/lib/python3.5/importlib/__init__.py in import_module, line 126
Python Executable: 	/home/goslnet.gov.lc/yfevrier/git/laisy/venv/laisyvenv/bin/python3.5
Python Version: 	3.5.2
Python Path: 	

['/home/goslnet.gov.lc/yfevrier/git/laisy',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/home/goslnet.gov.lc/yfevrier/git/laisy/venv/laisyvenv/lib/python3.5/site-packages',
 '/usr/lib/python35.zip']

Server time: 	Fri, 13 Jan 2017 09:01:04 -0600

Request Method: POST
Request URL: http://laisydev.slnet.bov.lc:8483/parcelmanager/authenticatedLogin/

Django Version: 1.8
Python Version: 3.5.2
Installed Applications:
('django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django_python3_ldap',
'crispy_forms',
'django_tables2',
'captcha',
'nocaptcha_recaptcha',
'parcelmanager',
'surveyplanmanager')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.middleware.security.SecurityMiddleware')

Traceback:
File "/srv/laisy/venv/laisyvenv/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
132. response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/goslnet.gov.lc/yfevrier/git/laisy/parcelmanager/views.py" in authenticatedLogin
131. user = authenticate(username=username, password=password)
File "/srv/laisy/venv/laisyvenv/lib/python3.5/site-packages/django/contrib/auth/init.py" in authenticate
66. for backend, backend_path in _get_backends(return_tuples=True):
File "/srv/laisy/venv/laisyvenv/lib/python3.5/site-packages/django/contrib/auth/init.py" in _get_backends
27. backend = load_backend(backend_path)
File "/srv/laisy/venv/laisyvenv/lib/python3.5/site-packages/django/contrib/auth/init.py" in load_backend
21. return import_string(path)()
File "/srv/laisy/venv/laisyvenv/lib/python3.5/site-packages/django/utils/module_loading.py" in import_string
26. module = import_module(module_path)
File "/usr/lib/python3.5/importlib/init.py" in import_module
126. return _bootstrap._gcd_import(name[level:], package, level)

Exception Type: ImportError at /parcelmanager/authenticatedLogin/
Exception Value: No module named 'django_python3_ldap.auth'

**Comment by DarnelleF** [comment]
sorry for reopening it but i need to get this working on linux as my hosting server is linux
anyway solutions for how i can solve this?

**Comment by DarnelleF** [comment]
once again.... i found out it was my error not the build but we are unable to login via microsoft active directory a question i would love an answer is if we only want to connect via AD do we need to specifiy only microsoft active direct directory settings or both ?

**Comment by etianen** [comment]
Only specify the AD settings if you're going to log in via AD. It's quite a
bit of work to configure for a particular ldap server, so good luck!

**Comment by DarnelleF** [comment]
thank you for your response!

**Comment by DarnelleF** [comment]
sorry to bother you again but your help would be greatly appreaciated
LDAP_AUTH_URL ="ldap://137.245.4.60:636"
LDAP_AUTH_FORMAT_USERNAME =
"django_python3_ldap.utils.format_username_active_directory"


LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "GOSL_DOM"
AUTHENTICATION_BACKENDS= ("django_python3_ldap.auth.LDAPBackend",
                          "django.contrib.auth.backends.ModelBackend",)
Request Method: POST
Request URL: http://127.0.0.1:8000/parcelmanager/authenticatedLogin/
Django Version: 1.8
Exception Type: RuntimeError
Exception Value:generator didn't stop after throw() Exception Location:
c:\python35\Lib\contextlib.py in __exit__, line 78 Python Executable:
C:\Users\yfevrier\Envs\landregtry1\Scripts\python.exe Python Version: 3.5.1
Python Path:

['C:\\Sites\\laisy',
 'C:\\Users\\yfevrier\\Envs\\landregtry1\\Scripts\\python35.zip',
 'C:\\Users\\yfevrier\\Envs\\landregtry1\\DLLs',
 'C:\\Users\\yfevrier\\Envs\\landregtry1\\lib',
 'C:\\Users\\yfevrier\\Envs\\landregtry1\\Scripts',
 'c:\\python35\\Lib',
 'c:\\python35\\DLLs',
 'C:\\Users\\yfevrier\\Envs\\landregtry1',
 'C:\\Users\\yfevrier\\Envs\\landregtry1\\lib\\site-packages']

Server time: Tue, 24 Jan 2017 14:35:08 -0400

it throws an error when we try and do it but when we use TLS=true
it tells us
LDAP connect failed: socket connection error while opening: [WinError
10060] A connection attempt failed because the connected party did not
properly respond after a period of time, or established connection failed
because connected host has failed to respond


note we are not incharge of the DNS, thats a different department

**Comment by etianen** [comment]
I think that there is a bug in the latest release of ldap3. Could I see the
output when you run "pip freeze"?

**Comment by DarnelleF** [comment]
thank you for all your assistance it wasnt due to your code but us missing
ldap_auth settings ( that is was throwing a bug ) as we have now integrated
your code into our application and it is working as intended

thou i would like to add some more notes to your readme file to make the
process of doing active directory via microsoft alittle easier for future
developers

**Comment by etianen** [comment]
I'll happily take a pull request that clarifies things. :)

**Comment by rokie582** [comment]
Hi,

I get the same error. I am pretty new to python and django. Could you please let me know what were the missing changes you have done to ldap_auth_settings?

socket connection error while opening: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by DarnelleF** [comment]
hi there imma try and assist 
normally a failure to respond was due ( in my experience ) to the wrong ip address. in my situation i was trying to authenticate with the wrong windows server which did not hold authentication. as of now i am not at work, so if this doesnt help Monday will be best for a proper response.

Regards

**Comment by etianen** [comment]
@rokie582 - can you provide the full console output of your error, please?

**Comment by rokie582** [comment]
Hi,

I am sorry for posting late. I had issues with my Pycharm license. Thanks a lot for responding


BELOW are my LDAP setting from settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'NameForm',
    'FEAuth',
    'django_python3_ldap',
]

AUTHENTICATION_BACKENDS = [
'django_python3_ldap.auth.LDAPBackend',
'django.contrib.auth.backends.ModelBackend',
'django.contrib.auth.backends.RemoteUserBackend',
]

# The URL of the LDAP server.
LDAP_AUTH_URL = "ldaps://<ldap server name>:636"



# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "ou=XXXX,dc=XXXX,dc=XXXX"

# The LDAP class that represents a user.
LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"



LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"


LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"


LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"


LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"


LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = 'XXXXXX'



# Set connection/receive timeouts (in seconds) on the underlying `ldap3` library.
LDAP_AUTH_CONNECT_TIMEOUT = 1000
LDAP_AUTH_RECEIVE_TIMEOUT = 1000



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}


Below is the console output.

LDAP connect succeeded
Internal Server Error: /FEAuth/
Traceback (most recent call last):
  File "C:\DEV\Python3.6.0\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\DEV\Python3.6.0\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\DEV\Python3.6.0\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rakesh.akula\PycharmProjects\first_django\FEAuth\views.py", line 27, in login_user
    user = authenticate(username=username, password=password)
  File "C:\DEV\Python3.6.0\lib\site-packages\django\contrib\auth\__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "C:\DEV\Python3.6.0\lib\site-packages\django\contrib\auth\__init__.py", line 115, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "C:\DEV\Python3.6.0\lib\site-packages\django_python3_ldap\auth.py", line 23, in authenticate
    return ldap.authenticate(*args, **kwargs)
  File "C:\DEV\Python3.6.0\lib\site-packages\django_python3_ldap\ldap.py", line 207, in authenticate
    return c.get_user(**kwargs)
  File "C:\DEV\Python3.6.0\lib\site-packages\django_python3_ldap\ldap.py", line 113, in get_user
    size_limit=1,
  File "C:\DEV\Python3.6.0\lib\site-packages\ldap3\core\connection.py", line 765, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "C:\DEV\Python3.6.0\lib\site-packages\ldap3\strategy\sync.py", line 142, in post_send_search
    responses, result = self.get_response(message_id)
  File "C:\DEV\Python3.6.0\lib\site-packages\ldap3\strategy\base.py", line 355, in get_response
    ref_response, ref_result = self.do_operation_on_referral(self._outstanding[message_id], responses[-2]['referrals'])
  File "C:\DEV\Python3.6.0\lib\site-packages\ldap3\strategy\base.py", line 747, in do_operation_on_referral
    referral_connection.open()
  File "C:\DEV\Python3.6.0\lib\site-packages\ldap3\strategy\sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "C:\DEV\Python3.6.0\lib\site-packages\ldap3\strategy\base.py", line 141, in open
    raise exception_history[0][1](exception_history[0][2])
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[21/Nov/2017 16:53:02] "POST /FEAuth/ HTTP/1.1" 500 124364

**Comment by etianen** [comment]
It looks like the LDAP server is referring you to another LDAP server, and
the new LDAP server can't be reached.

I think maybe you have some firewall or networking issues with your LDAP
server cluster.

**Comment by rokie582** [comment]
Hi @etianen ,

Thank you for your response. I found out that i was using wrong values in **LDAP_AUTH_SEARCH_BASE**. After i corrected it i moved a step further but i still get  'None' as return value.

Below is my console output. Could you please help me? Also could you please let me know the purpose of this attribute **LDAP_AUTH_USER_LOOKUP_FIELDS**

LDAP connect succeeded
LDAP user attributes empty
[24/Nov/2017 16:13:04] "POST /FEAuth/ HTTP/1.1" 200 1231

**Comment by etianen** [comment]
LDAP_AUTH_USER_LOOKUP_FIELDS is the names of the fields on the Django model
that uniquely identify the user. If you're using the normal Django auth
system, then the default of ("username",) is correct, since Django user
models have a unique constraint on the username field.

From your logs, it looks like the the LDAP server isn't including any
fields in the user. It's possible that there's some permissions issue on
the LDAP server restricting access to this data.
