### ISSUE TITLE
Disable formatting of LDAP_AUTH_CONNECTION_USERNAME

### ISSUE THREAD

**Issue by basilfx** [etianen/django-python3-ldap#96]
I've set up a OpenLDAP server using the [osixia/openldap](https://hub.docker.com/r/osixia/openldap/) Docker image. 

The default admin can login using `cn=admin,dc=example,dc=org` and password `admin`. I've added some example users in the `ou=people` group. My settings are:

```
LDAP_AUTH_URL = "ldap://localhost:389"
LDAP_AUTH_SEARCH_BASE = "ou=people,dc=example,dc=org"
LDAP_AUTH_CONNECTION_USERNAME = "cn=admin,dc=example,dc=org"
LDAP_AUTH_CONNECTION_PASSWORD = "admin"
```

When I try to login, I see that it tries to login the admin using `dn="uid=cn\3Dadmin,ou=people,dc=example,dc=org"` (according to log). This is obviously wrong.

When I change [this line](https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L174) and remove the `format_username(...)`, I can login and I can observe that my `LDAP_AUTH_CONNECTION_USERNAME` is passed as-is (distinguished name).

Is there a way to allow this, without modifying the source code? I could write a `LDAP_AUTH_FORMAT_USERNAME` method, but that also affects the actual login.

(Python 3.5.3, django-python3-ldap 0.10.0)

**Comment by etianen** [comment]
Place the admin user in the ou=people group, then change
LDAP_AUTH_CONNECTION_USERNAME to "admin"

All users must be in the same place in the LDAP tree.

**Comment by basilfx** [comment]
I don't want to have the admin in the `ou=people` group, because to me it is a special user. But I can understand the reason. 

For now I have come up with the following solution, which works fine for my use case:

```python
from django.conf import settings

from django_python3_ldap.utils import format_username_openldap


def format_username(fields):
    if "username" in fields:
        if fields["username"] == settings.LDAP_AUTH_CONNECTION_USERNAME:
            return settings.LDAP_AUTH_CONNECTION_USERNAME

    return format_username_openldap(fields)
```

I'll close the issue.

**Comment by etianen** [comment]
Seems like a reasonable solution. :)

**Comment by noubidossessi** [comment]
Hi dear @basilfx , 

Could you please tell me where you did put your fix code ? 
I have the same issue.
Regards

**Comment by basilfx** [comment]
@noubidossessi For what it is worth, just put it somewhere and set `LDAP_AUTH_FORMAT_USERNAME` to the `module.put.somehwere.method_name`.

**Comment by pedro-nonfree** [comment]
In debian the default slapd administrator is `cn=admin,dc=example,dc=com`. Modifying this behavior is not easy to me (that's why I'm here looking for a proxy to ldap stuff). And I still cannot "test" this package because of this. Also I cannot test that patch because I did not understood how to do it.

I'm thinking that the way to parse this variable would be to see if that string contains a comma then try `cn=admin,dc=example,dc=org`. If there is no comma the current default behavior now (admin).

Pointing to the most closest sources to the "possible solution" without success (seems slapd.conf is not working anymore in debian stretch)
https://wiki.debian.org/LDAP/OpenLDAPSetup#Missing_slapd.conf.3F
https://wiki.debian.org/LDAP/OpenLDAPSetup#Access_controls_for_subtree-specific_LDAP_Admins
https://www.openldap.org/doc/admin24/access-control.html
