### ISSUE TITLE
Bind with logging in user first

### ISSUE THREAD

**Issue by poffey21** [etianen/django-python3-ldap#99]
This is a design question - is there any particularly practical reason as to why you [bind the user before you bind the LDAP Manager credentials](https://github.com/etianen/django-python3-ldap/blob/2a05d41a7de819d81d212d22ed85f716196677ec/django_python3_ldap/ldap.py#L147-L180)?  

I've typically done the inverse, where if manager credentials were specified, I would bind with the LDAP Manager credentials first and then validate the logging in users credentials second. This approach gives you the ability to:

- Rebind with secondary user credentials
- OR simply validate the user credentials which won't count against them in LDAP if they've typed their password incorrectly. 

I typically don't recommend option two, but some users may desire that functionality.

I cannot see any benefit to ever providing LDAP Manager credentials within the context laid out for django-python3-ldap.

Oh, and side note, but I'm really happy this project's around. It fulfills a lot of needs that have been lacking in this space. Great work!

**Comment by etianen** [comment]
The logic is:

1. Check if the username and password are valid (LDAP bind)
2. Fetch the user data and use it to populate the Django user model (LDAP
query)

If the ldap user has permissions to perform the ldap query, then all is
good. However, it's common that the user doesn't have the required
permissions. This means you need to rebind before looking up the user
details. This changes the workflow to:

1. Check if the username and password are valid (LDAP bind)
2. Rebind as an admin user with query permissions
3. Fetch the user data and use it to populate the Django user model (LDAP
query)

**Comment by sonicblind** [comment]
Hi @etianen 

First of all, thank you for this great project!

I would like to ask similar to the original question.
The logic around binding to LDAP with this library does not fit my situation.

In our directory, all users have DN in format CN="Name Surname",OU=...
while their username is stored in sAMAccountName.

I need the users to be able to provide their username when logging in, instead of "Name Surname".
I do not plan to sync all LDAP users into Django DB, only add users on the fly when they login.

This means, I need to follow these steps for every login attempt:
- bind first with admin user to get full access connection with LDAP to be able to perform LDAP search
- perform LDAP search with a filter (&(objectclass=person)(sAMAccountName={username}))
- if such LDAP search fails, authentication also fails
- if such LDAP search finds excatly one user, learn user's DN
- use that DN and provided password to rebind the connection
- the rebind either fails or succeed

The library would currently always first try to bind with provided user username. For me it means the user would have to provide username in format "Name Surname", because that's the format of the DN in our LDAP.

I plan to rewrite the code to suit my needs, but wanted to ask you whether you plan to integrate solution to such situation at all? 

Thanks.
Martin

**Comment by etianen** [comment]
I'd not be averse to a PR that implements this logic.

I *do* worry about a proliferation of hard-to-understand config options
though. I wish LDAP didn't encourage such a huge variety of different login
mechanisms.

**Comment by sonicblind** [comment]
hi @etianen,  

I agree with you that LDAP offers just too many possibilities.
I thought about the PR, but found it difficult to implement the way I wanted, especially for cases where no LDAP_AUTH_CONNECTION_USERNAME is provided.

I was quite in a hurry with the project and I needed the functionality soon, so I quickly rewrote it to suit my authentication requirements. Maybe when I get time I will come back with a PR, just need to think about how to cover all possibilities. 

My version is [here](https://github.com/sonicblind/django-py3-ldap).

**Comment by etianen** [comment]
Understood, and thanks for linking to your version.

I sometimes wonder if it isn't easier for people to just fork this repo for
their needs, rather than implementing a massive configuration structure on
top of this one... :/
